# mysql
[database]
host = "127.0.0.1"
port = 3306
user = "root"
password = "pw"
db = "funds"
charset = "utf8"

[log]
level = 20 # NOTSET:0 DEBUG:10 INFO:20 WARNING:30 ERROR:40 CRITICAL:50

[percent]
percent = 0.2 # 每种基金的前20%

[mail]
server = "smtp.xx.com"
sender= "user@xx.com"
sender_password = "passwd"
